//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoservisApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnoservisEntities : DbContext
    {
        public TechnoservisEntities()
            : base("name=TechnoservisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarBrand> CarBrand { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<CarType> CarType { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Component> Component { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<RepairingRequest> RepairingRequest { get; set; }
        public virtual DbSet<ReparingComponent> ReparingComponent { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
