//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoservisApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public int HoursSpent { get; set; }
        public decimal Cost { get; set; }
        public string DefectCause { get; set; }
        public string RepairingDesc { get; set; }
    
        public virtual RepairingRequest RepairingRequest { get; set; }
    }
}
